-- REST_INFO를 기준으로 REST_REVIEW를 참고해야함
-- TODO: RIGHT OUTER JOIN을 써야 하는 이유...?
-- TODO: GROUP BY가 필요한 이유가 뭘까...
-- https://school.programmers.co.kr/questions/43609
SELECT
  i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS,
  ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i
RIGHT OUTER JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC;
